redis:
  restart: always
  tty: true
  image: 192.168.99.1:5000/redis
  stdin_open: true
pyapp:
  restart: always
  tty: true
  image: 192.168.99.1:5000/python-redis-demo:bMYBUILD
  links:
  - 'redis:'
  stdin_open: true
pyapplb:
  ports:
  - MYPORT:5000
  restart: always
  tty: true
  image: rancher/load-balancer-service
  links:
  - pyapp:pyapp
  stdin_open: true
