redis:
  restart: always
  tty: true
  image: 192.168.2.93:5002/proj1/redis
  stdin_open: true
pyapp:
  restart: always
  tty: true
  image: 192.168.2.93:5002/proj1/python-redis-demo:b$$BUILD_NUMBER$$
  links:
  - 'redis:'
  stdin_open: true
pyapplb:
  ports:
  - $$PORT_NUMBER$$:5000
  restart: always
  tty: true
  image: rancher/load-balancer-service
  links:
  - pyapp:pyapp
  stdin_open: true
